const menuList = [
  {
    name: 'Pancakes',
    cost: 5.99,
    image: 'images/pancakes.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'breakfast',
  },
  {
    name: 'Burger',
    cost: 8.99,
    image: 'images/burger.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Cake',
    cost: 9.99,
    image: 'images/cake.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'desserts',
  },
  {
    name: 'Coffee',
    cost: 5.99,
    image: 'images/coffee.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'drinks',
  },
  {
    name: 'Donat',
    cost: 3.99,
    image: 'images/donat.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'desserts',
  },
  {
    name: 'Eggs',
    cost: 7.99,
    image: 'images/eggs.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'breakfast',
  },
  {
    name: 'Fish',
    cost: 15.99,
    image: 'images/fish.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Fruits',
    cost: 10.99,
    image: 'images/fruits.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'desserts',
  },
  {
    name: 'Ice creame',
    cost: 7.99,
    image: 'images/ice_creame.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'desserts',
  },
  {
    name: 'Kebab',
    cost: 15.99,
    image: 'images/kebab.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Lemonade',
    cost: 5.99,
    image: 'images/lemonade.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'drinks',
  },
  {
    name: 'Muffin',
    cost: 5.99,
    image: 'images/muffins.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'desserts',
  },
  {
    name: 'Pie',
    cost: 6.99,
    image: 'images/pie.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'desserts',
  },
  {
    name: 'Pizza',
    cost: 7.99,
    image: 'images/pizza.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Salad-1',
    cost: 10.99,
    image: 'images/salad-1.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Salad-2',
    cost: 8.99,
    image: 'images/salad-2.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Shrimps',
    cost: 12.99,
    image: 'images/shrimps.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Smoothies',
    cost: 9.99,
    image: 'images/smoothies.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'breakfast',
  },
  {
    name: 'Soup-1',
    cost: 10.99,
    image: 'images/soup-1.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Soup-2',
    cost: 11.99,
    image: 'images/soup-2.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Steak',
    cost: 24.99,
    image: 'images/steak.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'lunch',
  },
  {
    name: 'Tea',
    cost: 4.99,
    image: 'images/tea.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'drinks',
  },
  {
    name: 'Yogurt',
    cost: 8.99,
    image: 'images/yogurt.jpeg',
    description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. At repudiandae sunt culpa! Perspiciatis similique ea temporibus ut quam nobis obcaecati exercitationem saepe porro nemo!',
    category: 'breakfast',
  },
]
